### 강의 추천 저장 작성
POST http://localhost:8080/lectures
Content-Type: application/json

{
  "id": 2,
  "lectureId": 2,
  "title": "Java Persistence API",
  "description": "김영한님의 JPA 실습 강의 입니다.",
  "image": "/images/lectures-01.png",
  "subject": "",
  "speaker": "김영한",
  "register": "이경희",
  "deadline": "2021-03-05"
}


> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.status)
    client.assert(response.status === 201, "Response status is not 201, it is " + response.status);
});
%}

### 강의 추천 전체 조회
GET http://localhost:8080/lectures
Accept: application/json

### 강의 추천 상세 조회
GET http://localhost:8080/lectures/2
Accept: application/json

### 강의 추천 개별 삭제
DELETE http://localhost:8080/lectures/1
Accept: application/json
###
