### 구인 작성
POST http://localhost:8080/recruits
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5NjI4NTQ0LCJpZCI6MSwiaXNzdWVkQXQiOjE2MTcwMzY1NDQsImp0aSI6ImY4Mjc3NzBiLTZjNTAtNGEzZS05Nzc1LTVjMzYxYTRhOGI2OCJ9.EbJ4sd2CkUlI1i5dCkQX7z9O8YMDFdr3dHhrem01hbU

{
  "company": "Naver",
  "title": "서비스를 함께 할 팀원을 모집합니다.",
  "location": "판교역 그린팩토리",
  "reward": 300000,
  "tag": "JAVA",
  "description": "웹/앱 서비스의 코어 개발을 담당하시며 빠르고 안정적인 서비스 구현의 핵심적인 역할을 수행하게 됩니다.",
  "deadline": "2021-05-30"
}

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.body)
    client.assert(response.status === 201, "Response status is not 201, it is " + response.status);
});
%}

### 구인 가져오기
GET http://localhost:8080/recruits/1
Accept: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MjgyMTYxLCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY2OTAxNjEsImp0aSI6IjgwNjUzNTA5LWQ0ZjUtNDg2Yy04N2ZhLTJmYjE4OGFlMTRlNyJ9.EuPFvVg2Hy9UqBs2yukp03emrAHza_FV_an761CaEew

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.body)
    client.assert(response.status === 200, "Response status is not 200, it is " + response.status);
});
%}

### 구인 업데이트
PUT http://localhost:8080/recruits
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MjgyMTYxLCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY2OTAxNjEsImp0aSI6IjgwNjUzNTA5LWQ0ZjUtNDg2Yy04N2ZhLTJmYjE4OGFlMTRlNyJ9.EuPFvVg2Hy9UqBs2yukp03emrAHza_FV_an761CaEew

{
  "id": 1,
  "register": "오성록",
  "company": "Never",
  "title": "회사이름 변경",
  "location": "판교역 그린팩토리",
  "reward": 300000,
  "tag": "JAVA",
  "description": "웹/앱 서비스의 코어 개발을 담당하시며 빠르고 안정적인 서비스 구현의 핵심적인 역할을 수행하게 됩니다.",
  "deadline": "2021-05-30"
}

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.body)
    client.assert(response.status === 200, "Response status is not 200, it is " + response.status);
});
%}

### 구인 삭제
DELETE http://localhost:8080/recruits/1
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MjgyMTYxLCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY2OTAxNjEsImp0aSI6IjgwNjUzNTA5LWQ0ZjUtNDg2Yy04N2ZhLTJmYjE4OGFlMTRlNyJ9.EuPFvVg2Hy9UqBs2yukp03emrAHza_FV_an761CaEew

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.status)
    client.assert(response.status === 204, "Response status is not 204, it is " + response.status);
});
%}

### 다른 조건 넣기
POST http://localhost:8080/recruits
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MjgyMTYxLCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY2OTAxNjEsImp0aSI6IjgwNjUzNTA5LWQ0ZjUtNDg2Yy04N2ZhLTJmYjE4OGFlMTRlNyJ9.EuPFvVg2Hy9UqBs2yukp03emrAHza_FV_an761CaEew

{
  "company": "우아한형제들",
  "title": "백엔드 개발자 모집",
  "location": "잠실역",
  "reward": 300000,
  "tag": "JAVA",
  "description": "우아한 개발자를 모십니다.",
  "deadline": "2021-05-20"
}


### 조건 구인 가져오기
GET http://localhost:8080/recruits?company=우아
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MjgyMTYxLCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY2OTAxNjEsImp0aSI6IjgwNjUzNTA5LWQ0ZjUtNDg2Yy04N2ZhLTJmYjE4OGFlMTRlNyJ9.EuPFvVg2Hy9UqBs2yukp03emrAHza_FV_an761CaEew

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.body)
    client.assert(response.status === 200, "Response status is not 200, it is " + response.status);
});
%}

### 구인 댓글 넣기
POST http://localhost:8080/recruits/2/reply
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MzkzOTA1LCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY4MDE5MDUsImp0aSI6IjhmMDg4ZDA1LWNiMzQtNDIwZS1iMjdmLWQ1MmM2NTQ3MGYyOSJ9.ztkPSHfTEcy9YrAvPxXcqhaykpMc3CSEt-Zvxv2xNIM

{
  "isChildId": false,
  "writer": "우아한형제들",
  "content": "좋은 구인 정보군요"
}

### 구인 댓글 가져오기
GET http://localhost:8080/recruits/2/reply
Accept: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MzkzOTA1LCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY4MDE5MDUsImp0aSI6IjhmMDg4ZDA1LWNiMzQtNDIwZS1iMjdmLWQ1MmM2NTQ3MGYyOSJ9.ztkPSHfTEcy9YrAvPxXcqhaykpMc3CSEt-Zvxv2xNIM

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.body)
    client.assert(response.status === 200, "Response status is not 200, it is " + response.status);
});
%}

### 구인 대댓글 작성
POST http://localhost:8080/recruits/2/reply
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MzkzOTA1LCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY4MDE5MDUsImp0aSI6IjhmMDg4ZDA1LWNiMzQtNDIwZS1iMjdmLWQ1MmM2NTQ3MGYyOSJ9.ztkPSHfTEcy9YrAvPxXcqhaykpMc3CSEt-Zvxv2xNIM

{
  "parentReplyId": 1,
  "isChildId": false,
  "writer": "토비",
  "content": "좋은 정보입니다."
}

### 구인 대대댓글 작성
POST http://localhost:8080/recruits/2/reply
Content-Type: application/json
Cookie: AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcnlUaW1lIjoxNjE5MzkzOTA1LCJpZCI6MSwiaXNzdWVkQXQiOjE2MTY4MDE5MDUsImp0aSI6IjhmMDg4ZDA1LWNiMzQtNDIwZS1iMjdmLWQ1MmM2NTQ3MGYyOSJ9.ztkPSHfTEcy9YrAvPxXcqhaykpMc3CSEt-Zvxv2xNIM

{
  "parentReplyId": 1,
  "isChildId": true,
  "writer": "토비333",
  "content": "2222"
}