### 중고거래 게시글 생성
POST http://localhost:8080/trading
Content-Type: application/json

{
  "writer": "KJJ",
  "titleImg" : "IMG URL",
  "address" : "서울특별시",
  "category" : "default",
  "description" : "content",
  "negotiation" : "true",
  "tradeType": "ALL",
  "title" : "MackBook 판매합니다.",
  "price": "10000"
}

> {%
client.test("Request executed successfully", function() {
    client.log("response.body" + response.status)
    client.assert(response.status === 201, "Response status is not 201, it is " + response.status);
});
%}

### 카테고리 종류 가져오기
GET http://localhost:8080/trading/categories
Accept: application/json


### defalutPage(아무런 검색조건이 없음) 중고거래 게시글 6개 보기 정렬기준 최근 작성된 글
GET http://localhost:8080/trading/pages
Accept: application/json


### 특정 게시글 가져오기
GET http://localhost:8080/trading/items?no=2
Accept: application/json




