server:
  port: 8080
spring:
  application:
    name: damoim-rest-api
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-db
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

damoim:
  file:
    pathPrefix: src/main/resources/static
    pathLast: /img/

---

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.130.14:3306/damoim?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
